program: src/pokedec/train.py
name: pokesweep
project: pokedec_train
entity: pokedec_mlops
method: bayes  # or 'grid' or 'random'
metric:
    goal: minimize
    name: val_loss
parameters:
    num-classes:
        values: [1000]
    lr:
        distribution: log_uniform_values
        min: 0.0001
        max: 0.1
    num-epochs:
        values: [20, 35, 50]
    batch-size:
        values: [32, 64]
    wd:
        distribution: log_uniform_values
        min: 0.0001
        max: 0.1
    seed:
        values: [42]
run_cap: 20
command:
  - ${env}
  - C:\Users\Damsgaard\Documents\Github\MLOps_2025\.venv\Scripts\python.exe
  - ${program}
  - ${args}

# To run in command-line:
# - First create sweep:
#     wandb sweep configs/sweep.yaml
# - Next run the agent (remember to give full path):
#     wandb agent entity/project/sweep_id
#     fx: pokedec_mlops/pokedec_mlops/imdqzsdv
